# Use a Node.js 14 base image
FROM node:18.13.0-alpine
# Set the working directory to /app
WORKDIR /app
# Copy the package.json and package-lock.json files to the container
COPY package*.json ./
# Install production dependencies
RUN npm ci --only=production
# Copy the rest of the application code to the container
COPY . .
# Build the application
RUN npm run build
# Expose port 8081
EXPOSE 8081
# Start the application server
CMD ["npm", "run", "start"]