# Use a Node.js 14 base image
FROM node:18.13.0-alpine
# Set the working directory to /app
WORKDIR /app
# Copy the package.json and package-lock.json files to the container
COPY package*.json ./
# Install production dependencies
RUN npm ci --only=production
RUN npm i nodemon
# Copy the rest of the application code to the container
COPY . .
# Expose port 8080
EXPOSE 8080
# Start the server
CMD ["npm", "start"]